### Login de Alice para obtener el token
# @name loginAlice
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "alice@alice.com",
    "password": "alice123"
}

### Crear un bus (Autorizado solo para Alice)
@tokenAlice = {{loginAlice.response.body.token}}
POST http://localhost:8080/bus
Content-Type: application/json
Authorization: Bearer {{tokenAlice}}

{
    "licensePlate": "XYZ789",
    "capacity": 50,
    "model": "Mercedes"
}

### Obtener lista de buses (Autorizado solo para Alice)
GET http://localhost:8080/bus
Content-Type: application/json
Authorization: Bearer {{tokenAlice}}

### Intento no autorizado con token inválido
GET http://localhost:8080/bus
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpbnZhbGlkIiwiaWF0IjoxNjk3OTI1NjAwLCJleHAiOjE2OTc5MjkyMDB9.MOCK_TOKEN
