### Crear un conductor (Autorizado solo para Alice)
@tokenAlice = {{loginAlice.response.body.token}}
POST http://localhost:8080/conductor
Content-Type: application/json
Authorization: Bearer {{tokenAlice}}

{
    "firstName": "Juan",
    "lastName": "Perez",
    "license": "ABC123"
}

### Obtener lista de conductores (Autorizado solo para Alice)
GET http://localhost:8080/conductor
Content-Type: application/json
Authorization: Bearer {{tokenAlice}}

### Intento no autorizado con token inválido
GET http://localhost:8080/conductor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpbnZhbGlkIiwiaWF0IjoxNjk3OTI1NjAwLCJleHAiOjE2OTc5MjkyMDB9.MOCK_TOKEN
