### Crear una ruta (Autorizado solo para Alice)
@tokenAlice = {{loginAlice.response.body.token}}
POST http://localhost:8080/ruta
Content-Type: application/json
Authorization: Bearer {{tokenAlice}}

{
    "name": "Ruta 101",
    "startLocation": "Punto A",
    "endLocation": "Punto B"
}

### Obtener lista de rutas (Autorizado solo para Alice)
GET http://localhost:8080/ruta
Content-Type: application/json
Authorization: Bearer {{tokenAlice}}

### Intento no autorizado con token inválido
GET http://localhost:8080/ruta
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpbnZhbGlkIiwiaWF0IjoxNjk3OTI1NjAwLCJleHAiOjE2OTc5MjkyMDB9.MOCK_TOKEN
